apiVersion: apps/v1
kind: Deployment
metadata:
  name: directus
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: directus
  template:
    metadata:
      labels:
        app: directus
    spec:
      containers:
        - name: directus
          image: directus/directus:latest
          ports:
            - containerPort: 8055
          envFrom:
            - configMapRef:
                name: directus-config
            - secretRef:
                name: directus-secret
          volumeMounts:
            - mountPath: /directus/uploads
              name: nfs-volume
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
      volumes:
        - name: nfs-volume
          persistentVolumeClaim:
            claimName: nfs-pvc-dev