apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-dev
  namespace: dev
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nfs_share/directus_dev
    server: 192.168.56.101
  claimRef:
    namespace: dev
    name: nfs-pvc-dev