namespace: "test"

image:
  tag: "test-latest"

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

##############################
